env = "Testnet" # SideSwap testnet server (Liquid Testnet network)
#env = "Prod" # SideSwap prod server (Liquid network)

# The dir for storing work files. The contents must be preserved.
work_dir = "/home/user/sideswap_manager/work_dir"

mnemonic = "<YOUR_MNEMONIC>"
script_variant = "wpkh" # Use "shwpkh" for nested segwit addresses

[ws_server]
listen_on = "127.0.0.1:3102"
